let header = document.querySelector("header");
let h3 = document.querySelector("header .container .address #h3");
let p = document.querySelector("header .container .address #p");
let swit = document.querySelector("header .container .switch");
let key = document.querySelector("header .container .key");
let on = document.querySelector("header .container .key .on");
let body = document.querySelector("body");
let boxone = document.querySelector(".section1 .container .one");
let boxtwo = document.querySelector(".section1 .container .two");
let boxthree = document.querySelector(".section1 .container .three");
let boxfour = document.querySelector(".section1 .container .four");
let boxonep = document.querySelector(".section1 .container .one .account p");
let boxtwop = document.querySelector(".section1 .container .two .account p");
let boxthreep = document.querySelector(".section1 .container .three .account p");
let boxfourp = document.querySelector(".section1 .container .four .account p");
let boxspanone = document.querySelector(".section1 .container .one span");
let boxspantwo = document.querySelector(".section1 .container .two span");
let boxspanthree = document.querySelector(".section1 .container .three span");
let boxspanfour = document.querySelector(".section1 .container .four span");
let H3 = document.querySelector(".section2 .container .H3");

let contain1 = document.querySelector("#contain1");
let contain2 = document.querySelector("#contain2");
let contain3 = document.querySelector("#contain3");
let contain4 = document.querySelector("#contain4");
let contain5 = document.querySelector("#contain5");
let contain6 = document.querySelector("#contain6");
let contain7 = document.querySelector("#contain7");
let contain8 = document.querySelector("#contain8");

let contain1p = document.querySelector("#contain1 .social p");
let contain2p = document.querySelector("#contain2 .social p");
let contain3p = document.querySelector("#contain3 .social p");
let contain4p = document.querySelector("#contain4 .social p");
let contain5p = document.querySelector("#contain5 .social p");
let contain6p = document.querySelector("#contain6 .social p");
let contain7p = document.querySelector("#contain7 .social p");
let contain8p = document.querySelector("#contain8 .social p");

let num1 = document.querySelector("#contain1 .text span");
let num2 = document.querySelector("#contain2 .text span");
let num3 = document.querySelector("#contain3 .text span");
let num4 = document.querySelector("#contain4 .text span");
let num5 = document.querySelector("#contain5 .text span");
let num6 = document.querySelector("#contain6 .text span");
let num7 = document.querySelector("#contain7 .text span");
let num8 = document.querySelector("#contain8 .text span");

let a = document.querySelectorAll(".contain1");
console.log(a);


key.addEventListener("click", () => {
    key.classList.toggle("key-bg");
    on.classList.toggle("left");
    header.classList.toggle("header-bg");
    swit.classList.toggle("swit");
    h3.classList.toggle("swit");
    H3.classList.toggle("swit");
    p.classList.toggle("p");
    body.classList.toggle("body");
    boxone.classList.toggle("card");
    boxtwo.classList.toggle("card");
    boxthree.classList.toggle("card");
    boxfour.classList.toggle("card");
    boxonep.classList.toggle("boxp");
    boxtwop.classList.toggle("boxp");
    boxthreep.classList.toggle("boxp");
    boxfourp.classList.toggle("boxp");
    boxspanone.classList.toggle("span");
    boxspantwo.classList.toggle("span");
    boxspanthree.classList.toggle("span");
    boxspanfour.classList.toggle("span");
    contain1.classList.toggle("card");
    contain2.classList.toggle("card");
    contain3.classList.toggle("card");
    contain4.classList.toggle("card");
    contain5.classList.toggle("card");
    contain6.classList.toggle("card");
    contain7.classList.toggle("card");
    contain8.classList.toggle("card");
    contain1p.classList.toggle("p");
    contain2p.classList.toggle("p");
    contain3p.classList.toggle("p");
    contain4p.classList.toggle("p");
    contain5p.classList.toggle("p");
    contain6p.classList.toggle("p");
    contain7p.classList.toggle("p");
    contain8p.classList.toggle("p");
    num1.classList.toggle("swit");
    num2.classList.toggle("swit");
    num3.classList.toggle("swit");
    num4.classList.toggle("swit");
    num5.classList.toggle("swit");
    num6.classList.toggle("swit");
    num7.classList.toggle("swit");
    num8.classList.toggle("swit");
});